### ISSUE TITLE
showremapped output even if topology change

### ISSUE THREAD

**Issue by stuartthebruce** [TheJJ/ceph-balancer#13]
What is the reason for `placementoptimizer.py showremapped` to raise an exception if the cluster topology has changed?
```
raise Exception("Cluster topology changed during information gathering (e.g. a pg changed state). "
```
Since this is a presumably a read-only operation how about changing that exception to a warning and outputting the currently remapped PG nonetheless?

**Comment by TheJJ** [comment]
This error occurs when the osdmap id changes during information gathering phase.
Unfortunately, I think, Ceph has zero support for transactions/atomic operations for its management.

So in order for the script to get all needed infos, it does multiple `ceph ... dump` commands. And since all these infos have to be combined, it's important that they're in sync. This is validated by comparing the osdmap id before and after the info gathering phase - when the ids don't match, something has changed, but due to the missing transaction support it's also impossible to figure out _what_ changed reliably).

**Comment by stuartthebruce** [comment]
Nuts. It is precisely when the cluster is most busy that running tools like this are the most helpful.
