### ISSUE TITLE
Cluster topology change recursion

### ISSUE THREAD

**Issue by stuartthebruce** [TheJJ/ceph-balancer#8]
Running `placementoptimizer.py` on my Pacific (15.2.16) cluster increases the `epoch` count, which triggers the following exception even when the cluster is idle,
```
[root@ceph-admin ~]# ./placementoptimizer.py -v balance --max-pg-moves 10
fsid 227d9741-3db8-4984-a522-6442c1739578
[2022-03-25 09:18:38,347] gathering cluster state via ceph api...
Traceback (most recent call last):
  File "./placementoptimizer.py", line 233, in <module>
    raise Exception("Cluster topology changed during information gathering (e.g. a pg changed state). "
Exception: Cluster topology changed during information gathering (e.g. a pg changed state). Wait for things to calm down and try again
```
What am I doing wrong?

**Comment by TheJJ** [comment]
Hi!
This error occurs when the osdmap version id increases while the script gathers data from the cluster.
It's a safety measure because in ceph there's unfortunately no transaction for queries: i have to call `ceph osd dump`, `ceph pg dump` etc one after the other, and hope the cluster state didn't change in between. And i validate this by getting the osdmap version before and after these calls, and then abort if the epochs don't match.
You can check this with `ceph osd dump | grep epoch`.

The osdmap epoch is increased whenever the osdmap changes, e.g. a scrub is finished, a pg is moved, ...
To see what the differences are, you can try this:
- `ceph pg dump > /tmp/pgdump-0`
- wait for a bit, 15s or something
- `ceph pg dump > /tmp/pgdump-1`
- `diff -u /tmp/pgdump-0 /tmp/pgdump-1`


My guess is if you pause your scrubs, it could be enough.
Or, if you want, I can add an override flag to ignore this check :)

**Comment by TheJJ** [comment]
Due to inactivity I'm gonna close this for now. If you have further questions, please just answer here or come by in the Matrix chat!
